language: node_js
node_js:
- '7.10.1'

env:
  global:
  - RELEASE_BRANCH=travis-tags-versions
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}

after_success:
- git config --local user.name "Travis CI"
- git config --local user.email "travis-ci@sudomesh.org"
- NODE_PACKAGE_VERSION=$(cat package.json | jq -r .version)
- git tag -a "$NODE_PACKAGE_VERSION" -m "$NODE_PACKAGE_VERSION"
- echo "BRANCH=$BRANCH"
- echo "RELEASE_BRANCH=$RELEASE_BRANCH"
- git push origin $NODE_PACKAGE_VERSION
