language: node_js
node_js:
- 7.10.1
env:
  global:
  - RELEASE_BRANCH=release
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - ENCRYPTION_LABEL=c8bf86153df9
  - DEPLOY_REPO=https://github.com/gobengo/monitor.git
before_install:
- REPO=`git config remote.origin.url`
# Decrypt travis secret for ssh private key
- ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
- ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
- ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
- ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
- mkdir -p ~/.ssh
- openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV
  -in sudomesh-travis-ci.enc -out ~/.ssh/sudomesh-travis-ci -d
- chmod 600 ~/.ssh/sudomesh-travis-ci
- eval $(ssh-agent -s)
- ssh-add ~/.ssh/sudomesh-travis-ci

script:
- |
  if [ "$REPO" = "$DEPLOY_REPO" ] && [ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]; then
    git config --local user.name "Travis CI"
    git config --local user.email "travis-ci@sudomesh.org"
    SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
    git remote add release_repo "$SSH_REPO"
    NODE_PACKAGE_VERSION=$(cat package.json | jq -r .version)
    if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      # PR into release branch. Just verify the tag isn't already claimed
      if [ "1" = "$(git ls-remote release_repo "refs/tags/$NODE_PACKAGE_VERSION" | wc -l)" ]; then
        echo "Tag already exists! Bump the package.json version to be a value that doesn't already exist"
        exit 1
      fi
    else
      # Running in release branch itself. We should create the tag
      git tag -a "$NODE_PACKAGE_VERSION" -m "$NODE_PACKAGE_VERSION"

      git push release_repo "$NODE_PACKAGE_VERSION"
    fi
  else
    echo "This is not the right branch or repo to do git tagging"
  fi
