language: node_js
node_js:
- '7.10.1'

env:
  global:
  - RELEASE_BRANCH=travis-tags-version
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}

jobs:
  include:
    - stage: dont tag
      name: wrong-branch-for-tag-release
      # require the branch name to be master
      if: "branch != env(RELEASE_BRANCH)"
      script:
      - echo "in wrong-branch-for-tag-release stage BRANCH=$BRANCH"

    - stage: tag release
      name: tag-release
      # require the branch name to be master
      if: "branch = env(RELEASE_BRANCH)"
      script:
      - echo "in tag-release stage BRANCH=$BRANCH"
      - NODE_PACKAGE_VERSION=$(cat package.json | jq -r .version)
      - echo "NODE_PACKAGE_VERSION=$NODE_PACKAGE_VERSION"
      - git tag -a $NODE_PACKAGE_VERSION
      - git push origin $NODE_PACKAGE_VERSION
